myBlog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myBlog.Models;
using myBlog.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace myBlog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            IQueryable<BlogPost> Posts = db.BlogPosts.AsQueryable();

            return View(Posts.OrderByDescending(d => d.Created).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(string searchStr, int? page)
        {
            var result = db.BlogPosts.AsQueryable();
            result = result.Where(p => p.Title.Contains(searchStr) ||
                        p.Body.Contains(searchStr) ||
                        p.Comments.Any(c => c.Body.Contains(searchStr) ||
                                       c.Author.FirstName.Contains(searchStr) ||
                                       c.Author.LastName.Contains(searchStr) ||
                                       c.Author.DisplayName.Contains(searchStr) ||
                                       c.Author.Email.Contains(searchStr)));
            int pageSize = 4;
            int pageNumber = page ?? 1;

            return View(result.OrderByDescending(d => d.Created).ToPagedList(pageNumber, pageSize));

        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if(String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);
            if(blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaUrl,Published,Slug")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilites.URLFriendly(blogPost.Title);
                if(String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if(db.BlogPosts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                if(ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/img/uploads/"), fileName));
                    blogPost.MediaUrl = "/img/uploads/" + fileName;
                }

                blogPost.Slug = Slug;
                blogPost.Created = DateTime.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,Updated,Title,Abstract,Body,MediaUrl,Published,Slug")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/img/uploads/"), fileName));
                    blogPost.MediaUrl = "/img/uploads/" + fileName;
                }

                db.Entry(blogPost).State = EntityState.Modified;
                blogPost.Updated = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if !IE]><!-->
<html lang="en">
 <!--<![endif]-->
<head>
    <title>John's Blog</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The Dream Multipurpose HTML5 Template">
    <meta name="author" content="CraftDzine">

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- CSS Global -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.css" rel="stylesheet" />
    <link href="~/Content/jquery.flexslider.css" rel="stylesheet" />
    <link href="~/Content/animate.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />

    <!-- WEB FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Raleway:500,800" rel="stylesheet" property="stylesheet" type="text/css" media="all" />

</head>
<body>
    <!-- Start Main Wrapper -->
    <div class="wrapper">
        <!-- Start Header -->
        <div class="header cd-header-block">
            <!--Start Navbar -->
            <div class="navbar mega-menu" role="navigation">
                <div class="container">
                    <!-- Start Brand and Mobile Display -->
                    <div class="menu-container">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".cd-navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- Search -->
                        <div class="header-right-sidebar">
                            <ul class="menu-icons-list">  
                                <li class="menu-icons">
                                    <i class="menu-icons-style search search-close search-btn fa fa-search"></i>
                                    <div class="search-open">
         
                                        @using (Html.BeginForm("Index", "BlogPosts", FormMethod.Post))
                                        {
                                            <input type="search" name="searchStr" class="form-control" id="nav-search" placeholder="Search" />
                                        }
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Search -->
                    <!-- Nav Links -->
                    <div class="collapse navbar-collapse cd-navbar">
                        <div class="menu-container">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Home", "Index", "BlogPosts")</li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li>@Html.Partial("_LoginPartial")</li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        @Html.ActionLink("Create New Blog", "Create", "BlogPosts")
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Navbar -->
        </div>
        <!-- End Header -->
            @RenderBody()
            <hr />
            <!-- Start Foooter-->
            <footer class="footer">
                <div class="main-footer">
                    <div class="container">
                        <div class="row">

                            <!-- Start Contact -->
                            <div class="col col-md-3 col-sm-6 footer-links">
                                <h3 class="cv-theme-widget-title">
                                   
                                </h3>

                                <ul class="contact-list-unstyled">
                            
                                </ul>
                                <div class="footer-copyright">
                                 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- End Foooter-->
        <!-- End Main Wrapper -->
        </div>
    </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

        <script src="~/Scripts/tinymce/tinymce.min.js"></script>
        <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>

        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/owl.carousel.min.js"></script>
        <script src="~/Scripts/filter.js"></script>
        <script src="~/Scripts/waypoints.min.js"></script>
        <script src="~/Scripts/jquery.counterup.min.js"></script>
        <script src="~/Scripts/jquery.flexslider-min.js"></script>
        <script src="~/Scripts/magnific-popup.min.js"></script>
        <script src="~/Scripts/jquery.selectBox.js"></script>
        <script src="~/Scripts/custom.js"></script>
        <script src="~/Scripts/jquery.dotdotdot.min.js"></script>

        @RenderSection("scripts", required: false)

        <script>
            jQuery(document).ready(function ($) {

                $(".blogThumbnailText").dotdotdot({

                    callback: function (isTruncated) { },
                    /* Function invoked after truncating the text.
                        Inside this function, "this" refers to the wrapper. */

                    ellipsis: "\u2026 ",
                    /* The text to add as ellipsis. */

                    height: 50,
                    /* The (max-)height for the wrapper:
                        null: measure the CSS (max-)height ones;
                        a number: sets a specific height in pixels;
                        "watch": re-measures the CSS (max-)height in the "watch". */

                    keep: null,
                    /* jQuery-selector for elements to keep after the ellipsis. */

                    tolerance: 0,
                    /* Deviation for the measured wrapper height. */

                    truncate: "word",
                    /* How to truncate the text: By "node", "word" or "letter". */

                    watch: "window",
                    /* Whether to update the ellipsis:
                        true: Monitors the wrapper width and height;
                        "window": Monitors the window width and height. */
                });

            });
        </script>
</body>





</html>