myBlog/Models/blogpost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myBlog.Models
{
    public class BlogPost
    {
        public int Id { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public string MediaUrl { get; set; }
        public bool Published { get; set; }
        public string Slug { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public BlogPost()
        {
            Comments = new HashSet<Comment>();
        }
    }
}

myBlog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myBlog.Models;
using myBlog.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace myBlog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            IQueryable<BlogPost> Posts = db.BlogPosts.AsQueryable();

            return View(Posts.OrderByDescending(d => d.Created).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(string searchStr, int? page)
        {
            var result = db.BlogPosts.AsQueryable();
            result = result.Where(p => p.Title.Contains(searchStr) ||
                        p.Body.Contains(searchStr) ||
                        p.Comments.Any(c => c.Body.Contains(searchStr) ||
                                       c.Author.FirstName.Contains(searchStr) ||
                                       c.Author.LastName.Contains(searchStr) ||
                                       c.Author.DisplayName.Contains(searchStr) ||
                                       c.Author.Email.Contains(searchStr)));
            int pageSize = 4;
            int pageNumber = page ?? 1;

            return View(result.OrderByDescending(d => d.Created).ToPagedList(pageNumber, pageSize));

        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if(String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);
            if(blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaUrl,Published,Slug")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilites.URLFriendly(blogPost.Title);
                if(String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if(db.BlogPosts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                if(ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/img/uploads/"), fileName));
                    blogPost.MediaUrl = "/img/uploads/" + fileName;
                }

                blogPost.Slug = Slug;
                blogPost.Created = DateTime.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,Updated,Title,Abstract,Body,MediaUrl,Published,Slug")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/img/uploads/"), fileName));
                    blogPost.MediaUrl = "/img/uploads/" + fileName;
                }

                db.Entry(blogPost).State = EntityState.Modified;
                blogPost.Updated = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myBlog.Models;
using Microsoft.AspNet.Identity;

namespace myBlog.Controllers
{
    [RequireHttps]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        //public ActionResult Index()
        //{
        //    var comments = db.Comments.Include(c => c.Author).Include(c => c.Post);
        //    return View(comments.ToList());
        //}

        // GET: Comments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comment comment = db.Comments.Find(id);
        //    if (comment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comment);
        //}

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.PostId = new SelectList(db.BlogPosts, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PostId,AuthorId,Body,Created,Updated,UpdateReason")] Comment comment, string bpslug)
        {
            if (ModelState.IsValid)
            {
                //db.Comments.Add(comment);
                //db.SaveChanges();
                //return RedirectToAction("Index");

                comment.AuthorId = User.Identity.GetUserId();
                comment.Created = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details", "BlogPosts", new { Slug = bpslug });
            }

            //ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorId);
            //ViewBag.PostId = new SelectList(db.BlogPosts, "Id", "Title", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var uId = User.Identity.GetUserId();
                if (IsCommentAuthor(uId, id.Value) || User.IsInRole("Admin") || User.IsInRole("Moderator"))
                {

                    Comment comment = db.Comments.Find(id);
                    if (comment == null)
                    {
                        return HttpNotFound();
                    }
                return View(comment);
                }
  
                //var bpId = db.Comments.Find(id).PostId;
                //var bpSlug = db.BlogPosts.Find(bpId).Slug;
                //return RedirectToAction("","",new { slug = bpSlug});
                //return RedirectToAction("Edit","Comments");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        private bool IsCommentAuthor(string UserId, int CommentId)
        {

            bool ca = db.Comments.All(c => c.Id == CommentId && c.AuthorId == UserId);

            return ca;
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PostId,AuthorId,Body,Created,Updated,UpdateReason")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            comment.Updated = DateTime.Now;
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorId);
            ViewBag.PostId = new SelectList(db.BlogPosts, "Id", "Title", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myBlog/Views/BlogPosts/Create.cshtml
@model myBlog.Models.BlogPost
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

<div class="col-md-2"></div>
@using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>BlogPost</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MediaUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="form-control" name="file" />
            @Html.ValidationMessageFor(model => model.MediaUrl, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control", id = "create" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Published)
                @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div class="col-md-2"></div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#create'
            })
        })
    </script>
}

myBlog/Views/BlogPosts/Delete.cshtml
@model myBlog.Models.BlogPost

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

myBlog/Views/BlogPosts/Details.cshtml
@model myBlog.Models.BlogPost
@using Microsoft.AspNet.Identity;


<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="text-center">
                <h2>@Model.Title</h2>
            </div>
        </div>
    </div>
</div>
<!-- Start Blog-->

<section class="main-contain">
    <div class="container">
    <div class="col-md-1"></div>
        <div class="row">
            <div class="col-md-10 col-sm-7 col-xs-12">
                <div class="cv-theme-pa-30">
                    <div class="standard-post-thumbnail">
                        <div class="post-image-block">
                            @if (Model.MediaUrl != null)
                            {
                                <img src="@Url.Content(Model.MediaUrl)" alt="" class="img-responsive">
                            }
                        </div>
                        <div class="blog-dis">
                            <h2 class="entry-title">@Model.Title</h2>
                            <p class="post-meta">By <span class="author vcard">Author</span>  |  <span class="published">@Model.Created.ToString("MM/dd/yyyy")</span></p>
                            @Html.Raw(@Model.Body)
                        </div>
                    </div>
                </div>
                <div class="blog-comments-block cv-theme-30">
                    <h1 class="comments_title">@Model.Comments.Count() Comments</h1>

                    @foreach (var comment in Model.Comments.OrderByDescending(c => c.Created))
                    {
                        <div class="media comment_section">
                                @if (comment.Author.Avatar == null)
                                {
                                    <div class="pull-left post_comments">
                                        <a href="#"><img src="~/img/avatars/default.png" class="img-circle" alt="" /></a>
                                    </div>
                                }
                                else
                                {
                                    <div class="pull-left post_comments">
                                        <a href="#"><img src="@Url.Content(comment.Author.Avatar)" class="img-circle" alt="" /></a>
                                    </div>
                                }
                            <div class="media-body post_reply_comments">
                                <h4>@comment.Author.DisplayName</h4>
                                <h6>@comment.Created.ToString("MM/dd/yyyy HH:mm")</h6>
                                @Html.Raw(comment.Body)
                            </div>
                        </div>
                        if (User.IsInRole("Admin") || User.IsInRole("Moderator") || comment.AuthorId == HttpContext.Current.User.Identity.GetUserId())
                        {
                            @Html.ActionLink("Edit", "Edit", "Comments", new { id = comment.Id }, new { @class = "btn btn-xs btn-info" })
                            @Html.ActionLink("Delete", "Delete", "Comments", new { id = comment.Id }, new { @class = "btn btn-xs btn-info" })
                        }
                    }
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="blog-post-comment clearfix">
                        <div class="form-main">
                            @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken();

                                @Html.Hidden("PostId", Model.Id)
                                @Html.Hidden("bpSlug", Model.Slug)

                                <p class="text">
                                    <textarea name="Body" class="feedback-input" id="comment" placeholder="Comment"></textarea>
                                </p>

                                <div class="submit">
                                    <button type="submit" class="form-button">Post Comment</button>
                                </div>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</section>

<!-- End Blog-->

myBlog/Views/BlogPosts/Edit.cshtml
@model myBlog.Models.BlogPost

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
 
    
<div class="form-horizontal">
    <h4>BlogPost</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Created)
    @Html.HiddenFor(model => model.MediaUrl)
    @Html.HiddenFor(model => model.Slug, new { slug = Model.Slug })

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MediaUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="image" type="file" class="form-control" id="fileUpload" />
            @Html.ValidationMessageFor(model => model.MediaUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Published)
                @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control", id ="editor" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#editor'
            })
        })
    </script>

}

myBlog/Views/BlogPosts/Index.cshtml
@using myBlog.Models;
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BlogPost>

<!-- Start Breadcrumb -->
<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="text-center">
                <h2>John's Blog</h2>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumb -->


@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}


<!-- Start Blog-->
<section class="main-contain">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-sm-6 col-xs-12 cv-theme-pa-30">
                    <div class="standard-post-thumbnail">
                        @if (item.MediaUrl != null)
                        {
                            <div class="post-image-block img"> 
                                <a href="blog_signal.html"><img src="@item.MediaUrl" alt="" class="img-responsive" style="height:367px; object-fit:contain;"></a>
                            </div>
                        }
                        <div class="blog-dis">
                            <h2 class="entry-title">@Html.ActionLink(item.Title, "Details", new { slug = item.Slug })</h2>
                            <p class="post-meta">By <span class="author vcard"><a title="Posts By Admin" href="#">Admin</a></span>  |  <span class="published">@item.Created</span> </p>
                            <div class = 'blogThumbnailText'>@Html.Raw(item.Body)</div>
                        </div>
                    </div>
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                        
                   
           
                    
                    
                </div>
            }
        </div>
        <!-- Start Pagination-->
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        <!-- End Pagination-->
    </div>
</section>

<!-- End Blog-->